# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'query1.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1067, 740)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(450, 620, 101, 41))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(110, 180, 211, 131))
        self.checkBox_3 = QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(30, 20, 161, 31))
        self.checkBox_4 = QCheckBox(self.groupBox_2)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(30, 60, 171, 31))
        self.checkBox_5 = QCheckBox(self.groupBox_2)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(30, 100, 171, 31))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(110, 330, 211, 281))
        self.checkBox_6 = QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(30, 20, 181, 41))
        self.checkBox_7 = QCheckBox(self.groupBox_3)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(30, 70, 181, 51))
        self.checkBox_8 = QCheckBox(self.groupBox_3)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(30, 130, 171, 51))
        self.checkBox_9 = QCheckBox(self.groupBox_3)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(30, 190, 171, 41))
        self.checkBox_10 = QCheckBox(self.groupBox_3)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(30, 240, 171, 41))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(400, 40, 211, 211))
        self.checkBox_11 = QCheckBox(self.groupBox_4)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(30, 20, 181, 31))
        self.checkBox_12 = QCheckBox(self.groupBox_4)
        self.checkBox_12.setObjectName(u"checkBox_12")
        self.checkBox_12.setGeometry(QRect(30, 60, 171, 41))
        self.checkBox_13 = QCheckBox(self.groupBox_4)
        self.checkBox_13.setObjectName(u"checkBox_13")
        self.checkBox_13.setGeometry(QRect(30, 110, 181, 41))
        self.checkBox_14 = QCheckBox(self.groupBox_4)
        self.checkBox_14.setObjectName(u"checkBox_14")
        self.checkBox_14.setGeometry(QRect(30, 160, 181, 31))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(400, 460, 211, 131))
        self.checkBox_18 = QCheckBox(self.groupBox_5)
        self.checkBox_18.setObjectName(u"checkBox_18")
        self.checkBox_18.setGeometry(QRect(30, 20, 171, 41))
        self.checkBox_19 = QCheckBox(self.groupBox_5)
        self.checkBox_19.setObjectName(u"checkBox_19")
        self.checkBox_19.setGeometry(QRect(30, 70, 181, 41))
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(400, 270, 211, 161))
        self.checkBox_15 = QCheckBox(self.groupBox_6)
        self.checkBox_15.setObjectName(u"checkBox_15")
        self.checkBox_15.setGeometry(QRect(30, 20, 171, 31))
        self.checkBox_16 = QCheckBox(self.groupBox_6)
        self.checkBox_16.setObjectName(u"checkBox_16")
        self.checkBox_16.setGeometry(QRect(30, 70, 181, 31))
        self.checkBox_17 = QCheckBox(self.groupBox_6)
        self.checkBox_17.setObjectName(u"checkBox_17")
        self.checkBox_17.setGeometry(QRect(30, 115, 171, 31))
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(720, 50, 211, 261))
        self.checkBox_20 = QCheckBox(self.groupBox_7)
        self.checkBox_20.setObjectName(u"checkBox_20")
        self.checkBox_20.setGeometry(QRect(20, 30, 181, 41))
        self.checkBox_21 = QCheckBox(self.groupBox_7)
        self.checkBox_21.setObjectName(u"checkBox_21")
        self.checkBox_21.setGeometry(QRect(20, 90, 181, 51))
        self.checkBox_22 = QCheckBox(self.groupBox_7)
        self.checkBox_22.setObjectName(u"checkBox_22")
        self.checkBox_22.setGeometry(QRect(20, 160, 181, 41))
        self.checkBox_23 = QCheckBox(self.groupBox_7)
        self.checkBox_23.setObjectName(u"checkBox_23")
        self.checkBox_23.setGeometry(QRect(20, 220, 191, 41))
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(720, 340, 211, 281))
        self.checkBox_24 = QCheckBox(self.groupBox_8)
        self.checkBox_24.setObjectName(u"checkBox_24")
        self.checkBox_24.setGeometry(QRect(20, 30, 191, 41))
        self.checkBox_25 = QCheckBox(self.groupBox_8)
        self.checkBox_25.setObjectName(u"checkBox_25")
        self.checkBox_25.setGeometry(QRect(20, 70, 191, 51))
        self.checkBox_26 = QCheckBox(self.groupBox_8)
        self.checkBox_26.setObjectName(u"checkBox_26")
        self.checkBox_26.setGeometry(QRect(20, 120, 191, 41))
        self.checkBox_27 = QCheckBox(self.groupBox_8)
        self.checkBox_27.setObjectName(u"checkBox_27")
        self.checkBox_27.setGeometry(QRect(20, 170, 181, 41))
        self.checkBox_28 = QCheckBox(self.groupBox_8)
        self.checkBox_28.setObjectName(u"checkBox_28")
        self.checkBox_28.setGeometry(QRect(20, 220, 181, 51))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(110, 40, 211, 131))
        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(30, 20, 171, 41))
        self.checkBox_2 = QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(30, 80, 171, 41))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1067, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u7ee7\u7eed", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"contact", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"s_id", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"s_phone", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"QQ", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"course", None))
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"course_id", None))
        self.checkBox_7.setText(QCoreApplication.translate("MainWindow", u"course_name", None))
        self.checkBox_8.setText(QCoreApplication.translate("MainWindow", u"hours", None))
        self.checkBox_9.setText(QCoreApplication.translate("MainWindow", u"credit", None))
        self.checkBox_10.setText(QCoreApplication.translate("MainWindow", u"t_id", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"parents", None))
        self.checkBox_11.setText(QCoreApplication.translate("MainWindow", u"relation", None))
        self.checkBox_12.setText(QCoreApplication.translate("MainWindow", u"s_id", None))
        self.checkBox_13.setText(QCoreApplication.translate("MainWindow", u"p_name", None))
        self.checkBox_14.setText(QCoreApplication.translate("MainWindow", u"p_phone", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"department", None))
        self.checkBox_18.setText(QCoreApplication.translate("MainWindow", u"d_id", None))
        self.checkBox_19.setText(QCoreApplication.translate("MainWindow", u"d_name", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"sc", None))
        self.checkBox_15.setText(QCoreApplication.translate("MainWindow", u"s_id", None))
        self.checkBox_16.setText(QCoreApplication.translate("MainWindow", u"course_id", None))
        self.checkBox_17.setText(QCoreApplication.translate("MainWindow", u"score", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"teacher", None))
        self.checkBox_20.setText(QCoreApplication.translate("MainWindow", u"t_id", None))
        self.checkBox_21.setText(QCoreApplication.translate("MainWindow", u"t_sex", None))
        self.checkBox_22.setText(QCoreApplication.translate("MainWindow", u"t_name", None))
        self.checkBox_23.setText(QCoreApplication.translate("MainWindow", u"d_id", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"student", None))
        self.checkBox_24.setText(QCoreApplication.translate("MainWindow", u"s_id", None))
        self.checkBox_25.setText(QCoreApplication.translate("MainWindow", u"s_name", None))
        self.checkBox_26.setText(QCoreApplication.translate("MainWindow", u"age", None))
        self.checkBox_27.setText(QCoreApplication.translate("MainWindow", u"s_sex", None))
        self.checkBox_28.setText(QCoreApplication.translate("MainWindow", u"class_id", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"class", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"class_id", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"d_id", None))
    # retranslateUi

